//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecipeBook.Exception {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MyRecipeBook.Exception.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string VALIDATION_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_NAME_REQUIRED", resourceCulture);
            }
        }
        
        public static string VALIDATION_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        public static string VALIDATION_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_INVALID", resourceCulture);
            }
        }
        
        public static string VALIDATION_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        public static string VALIDATION_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
    }
}
